### PR TITLE
Add notices to Windows Installer package

### PR DESCRIPTION
**Pull request by heaths**

### CODE REVIEW

**Comment by heaths** [comment]
Seems hyperlinks in the RTF file are not clickable. I remembered incorrectly how they "fixed" this by introducing a Hyperlink control in Windows Installer 5.0 (I may have been thinking more about changes we made for VS and .NET installers to support clickable links in our custom bootstrapper-chainers). They could still be copied and pasted, but if making them clickable is important, I can re-define the custom dialog (after adding the "license" dialog back in, it was no longer necessary to define a custom dialog set) and add a Hyperlink control instead.

**Review by danieljurek — APPROVED** [review]
Tested the MSI produced in the PR. This looks good to me. The user doesn't technically need to check the box and agree because they're notices but I don't think that makes a huge difference here.

**Comment by heaths** [comment]
> Tested the MSI produced in the PR. This looks good to me. The user doesn't technically need to check the box and agree because they're notices but I don't think that makes a huge difference here.

Ah, good point. I can remove that.

**Review by danieljurek — APPROVED** [review]
Looks great. Updating the notices text makes things more clear. Thanks again!

**Pull request merged**
