### PR TITLE
Update swa.go

### PR DESCRIPTION
**Pull request by sinedied**
update SWA CLI to latest version as many bugs were fixed

### CODE REVIEW

**Review by wbreza — APPROVED** [review]
LGTM

**Comment by vhvb1989** [comment]
@ellismg @rajeshkamal5050 , do we  want this for this week's release?

**Comment by rajeshkamal5050** [comment]
> @ellismg @rajeshkamal5050 , do we want this for this week's release?

Seems a big bump. We can take it in for next release.

**Review by ellismg — APPROVED** [review]
LGTM - I think waiting for the next release is good.

**Pull request merged**
