### PR TITLE
Add option to suppress readme

### PR DESCRIPTION
**Pull request by alexweininger**

### CODE REVIEW

**Review by bwateratmsft — APPROVED** [review]

**Review by ellismg — APPROVED** [review]

**Comment by bwateratmsft** [comment]
@danieljurek Do you know how to get the checks to rerun here? They shouldn't have failed...

**Comment by alexweininger** [comment]
They are failing because

> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

**Comment by alexweininger** [comment]
https://github.com/Azure/azure-dev/pull/4471

**Comment by bwateratmsft** [comment]
Merged! Thanks @alexweininger!

**Pull request merged**
