### PR TITLE
Fix Playwright test fail in todo-nodejs-mongo

### PR DESCRIPTION
**Pull request by hongli750210**
Fixes issue https://github.com/Azure/azure-dev/issues/246

Change files: templates/todo/common/tests/todo.spec.ts
Add setTimeOut is used to wait for the page data to full load.

@rajeshkamal5050 for notification.

### CODE REVIEW

**Review by ellismg — CHANGES_REQUESTED** [review]
Instead of inserting this 5 second delay, could we instead pass `{ waitUntil: 'networkidle' }` to the initial `page.goto` call as an option?

Alternately, use https://playwright.dev/docs/api/class-locator#locator-wait-for to wait for a specific element to be loaded.

If we are going to keep this timeout, let's at least use https://playwright.dev/docs/api/class-page#page-wait-for-timeout instead of this explicit promise with a `then`

**Comment by hongli750210** [comment]
I think it's better to pass `{ waitUntil: 'networkidle' }` to the initial page.goto call as an option. So the code has now been corrected according to this idea.

**Review by ellismg — APPROVED** [review]
LGTM

**Review by wbreza — APPROVED** [review]
LGTM

**Comment by vhvb1989** [comment]
pipeline is currently broken after this PR:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1814636&view=logs&j=9392ca66-1ee4-52af-022d-b22076a99114&t=6db148d5-c790-543c-3e98-57830bb8eafe&l=162

Change:
image

image

@hongli750210 , any ideas?

**Comment by hongli750210** [comment]
@vhvb1989 
Replace `：` with `: ` to fix the problem you mentioned. Can I still upload a new version after the code has been merged?

**Comment by rajeshkamal5050** [comment]
@hongli750210 additional syntax fix was made by @ellismg. Should be good now.
- https://github.com/Azure/azure-dev/pull/546

**Pull request merged**
