### PR TITLE
Remove Old C# Sample per @jongio

### PR DESCRIPTION
**Pull request by isaacrlevin**
Based on conversation with @jongio, removing an old /api/csharp sample

### CODE REVIEW

**Comment by jongio** [comment]
@rajeshkamal5050 - I was talking with Isaac today and I don't think this is being used anymore, since we started with c#/mongo and then moved to c#/cosmos-sql instead.  If not used, I suggest we delete it to minimize maintenance costs.

**Review by vhvb1989 — APPROVED** [review]

**Comment by vhvb1989** [comment]
I verified the folder is not used by any of the todo projects. It is totally dead code in there :)

**Review by ellismg — APPROVED** [review]

**Comment by vhvb1989** [comment]
@weikanglim  @ellismg , there's no templates to sync or test. The code is death/abandoned code.

**Pull request merged**
