### PR TITLE
Show README file after successful init/up

### PR DESCRIPTION
**Pull request by karolz-ms**
Fixes https://github.com/Azure/azure-dev/issues/148

### CODE REVIEW

**Review by ellismg — COMMENTED** [review]
Should we do this as part of `up`?  I am worried that `up` is something folks will run as part of their inner loop and causing a README.md to pop up each time you do that gesture will be frustrating.

I feel like `init` is a place where it makes sense to do this sort of "first run" stuff, but if `up` is something we think of as an inner loop command, we should strongly consider not doing this (or perhaps provide some setting I can add to `settings.json` to stop this from happening).

**Comment by karolz-ms** [comment]
> Should we do this as part of `up`? I am worried that `up` is something folks will run as part of their inner loop and causing a README.md to pop up each time you do that gesture will be frustrating.
> 
> I feel like `init` is a place where it makes sense to do this sort of "first run" stuff, but if `up` is something we think of as an inner loop command, we should strongly consider not doing this (or perhaps provide some setting I can add to `settings.json` to stop this from happening).

This is very good point. @savannahostrowski what do you say?

**Comment by savannahostrowski** [comment]
To be clear, if we include the logic to open the preview of the markdown on `init` isn't the behaviour just that the user will see it the first time they run `up` and then not again? Doesn't `init` in `up` sort of no-op if the project has already been initialized by azd?

I'd rather not introduce this as a setting in settings.json for the time being. In my experience, we should be pretty judicious with what we created user-exposed settings for (trying to avoid settings becoming cluttered).

**Comment by karolz-ms** [comment]
@savannahostrowski and I chatted; I am going to change this PR to only open README at the end of `up` if `up` was invoked in the context of a folder that does not have `azure.yaml` (first run for a new app instance).

**Comment by karolz-ms** [comment]
@ellismg thanks for your feedback, I believe it is addressed now, please take another look--thx!

**Review by ellismg — APPROVED** [review]
Love the solution!  Looks Great to Me!

**Pull request merged**
