### PR TITLE
fix: remove undesirable whitespace trimming in `main.bicept` app-host template

### PR DESCRIPTION
**Pull request by wave-ys**
There is an undesirable whitespace trimming character `-` in [cli/azd/resources/apphost/templates/main.bicept](https://github.com/Azure/azure-dev/blob/c56e342744c79bb0a4d5fce62594fe1a7335e25b/cli/azd/resources/apphost/templates/main.bicept#L94), causing this issue: [https://github.com/dotnet/aspire-samples/issues/372](https://github.com/dotnet/aspire-samples/issues/372).

It is likely that whenever an .NET Aspire project uses Azure Blob Storage and executs `azd provision`, this trimming character could merge two lines, generating `main.bicept` like this:

> output STORAGE_BLOBENDPOINT string = storage.outputs.**blobEndpointoutput** AZURE_VOLUMES_STORAGE_ACCOUNT string = resources.outputs.AZURE_VOLUMES_STORAGE_ACCOUNT

And then this error would be thrown:

> /var/folders/ld/z326vtn52c579_v_tn_p3wn00000gn/T/azd-infra781087368/main.bicep(75,54) : Error BCP053: The type "outputs" does not contain property "**blobEndpointoutput**". Available properties include "blobEndpoint", "queueEndpoint", "tableEndpoint".
/var/folders/ld/z326vtn52c579_v_tn_p3wn00000gn/T/azd-infra781087368/main.bicep(75,73) : Error BCP019: Expected a new line character at this location.

This PR fixes this issue.

### CODE REVIEW

**Comment by wave-ys** [comment]
> @wave-ys please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Review by vhvb1989 — APPROVED** [review]
Thank you @wave-ys

**Review by ellismg — APPROVED** [review]

**Pull request merged**
