### PR TITLE
Pipe command output to stdout, stderr with --debug

### LINKED ISSUE #2432: [Issue]
- [x] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.0.2 (commit 145e046b1ea9394bd4e1b1d539eb32e860d692fb)

**Describe the bug**
There is no way to troubleshoot script hooks because output does't appear to be available even if running `azd up --debug`. No log file, nothing.

**To Reproduce**
Add a hook like https://github.com/heaths/azcrypto/blob/553f98cbb9dedd76534778050ad06eea4818b135/azure.yaml#L9. Run it with necessary parameters, and notice that - even when passed `--debug` - all you see is something like this:

```text
Executing postprovision hook => /tmp/azd-postprovision-3919396641.sh
2023/06/16 14:14:25 hooks_runner.go:148: Executing script '/tmp/azd-postprovision-3919396641.sh'
2023/06/16 14:17:34 command_runner.go:132: Run exec: ' /tmp/azd-postprovision-3919396641.sh' , exit code: 0
```

That said, at the very end - not during - anything written to stderr was shown.

**Expected behavior**
stdout and stderr should be redirected to azd's own stdout and stderr - at least when passing `--debug` or, perhaps better, a `--verbose` (I don't need to see tons of polling messages for resources like Managed HSM that take a very long time to provision.

Or at least write those to a log and tell me the log path before you execute so I can tail it.

### PR DESCRIPTION
**Pull request by heaths**
Resolves #2432

### CODE REVIEW

**Comment by heaths** [comment]
Currently, this is stateless and assumes each call to `Write` is one or more lines. This may not always be the case. I could instead buffer, but would need to add a `Close` method or something to `sanitizingLogWriter` to make sure the last line (if any) is written to the underlying `io.Writer`.

**Comment by weikanglim** [comment]
@heaths `--debug` flag should set `commandRunner.debugLogEnabled` which should then send the stdout/stderr output for commands to stderr using the `log` library. I'm looking into what hooks does here that maybe isn't working correctly.

**Comment by heaths** [comment]
`commandRunner` never called into the `log` package. Regardless, the point is to write them as writes are happening or the whole point is moot: to diagnose commands - to see if they are hung or stuck, whatever - you need to see stdout and/or stderr as they are written. Buffering them as was done before defeats the purpose of this PR and associated issue.

**Comment by weikanglim** [comment]
`log` usage is [here](https://github.com/Azure/azure-dev/blob/cda6e43d7bed02d11cbb2fe3d3d98542e253cd5c/cli/azd/pkg/exec/command_runner.go#L153). We should definitely change the implementation to unbuffered as you have with `MultiWriter`

**Comment by weikanglim** [comment]
Different way of doing this may be to set under-the-covers `Interactive: true` when running hook and `--debug` is enabled [here](https://github.com/Azure/azure-dev/blob/f2aafb04f11b829b2faa699c6734a299800da183/cli/azd/pkg/ext/hooks_runner.go#L132).

Alternatively, we've generally funneled data through `log` package which generally means `stderr` when `--debug` is enabled, so that a user can have clean `stdout` output that represents the non-debug output, and `stderr` that contains verbose and debug output. hooks are obviously going to be the exception here no matter what we take, but the change in command_runner will affect azd calling into other tools as well. It may also be the right behavioral change to make.

**Comment by heaths** [comment]
How I output the data isn't really much of the concern here - as long as we're sanitizing it. If instead of `fmt.Fprintf` I call some `log.Print` (or whatever), I have no problem with that - especially if it takes care of the space prefix e.g., "   ", itself uniformly like request/response logging.

My main concern is that stdout/stderr is written to the terminal as it's happening. The existing code buffers it and prints it at the end, but that's completely useless if a command is "hung" e.g., waiting for user input unexpectedly, taking a long time with no timeout, etc. That's why many other CLIs log command output when debugging output.

**Comment by heaths** [comment]
The team went a different way on this, I believe.

**Pull request closed without merging**
