### PR TITLE
chore: pkg imported more than once

### PR DESCRIPTION
**Pull request by testwill**

### CODE REVIEW

**Review by weikanglim — APPROVED** [review]

**Review by ellismg — CHANGES_REQUESTED** [review]
Thanks for noticing this and submitting a fix, @testwill!  I am wondering if instead we should just stop importing the internal package as `azdinternal` and just use the default import name of `internal`.  That might play nicer with folks doing development in VS Code and other editors where I think the default workflow with intellisense may lead to this internal reference coming back in the future?

**Review by ellismg — APPROVED** [review]
I reworked the import path.  Thanks for kicking off the conversation @testwill!

**Pull request merged**
