### PR TITLE
Add `--scope` to login

### PR DESCRIPTION
**Pull request by weikanglim**
Even after a user performs interactive auth login, with local credentials stored on disk, there are cases where reauthentication is required. In some cases, a Conditional Access Policy has been applied to a specific resource (in OAuth terms, scope) in the tenant, resulting in additional authentication challenges. To satisfy those challenges, reauthentication with the desired scope is required.

`--scope` is currently an experimental flag, thus hidden by default. A follow-up PR will take advantage of this to provide the user with follow-up hints for reauthentication when specific auth errors are encountered.

Read more about developer guidance for Conditional Access Policy here: https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-conditional-access-dev-guide

### CODE REVIEW

**Review by ellismg — APPROVED** [review]
LGTM, I think this is going to be really nice to have in the product for helping users who are in restricted environments and find themselves wedged.  It should help unblock a lot of stuff that previously had very nasty workarounds.

**Comment by vhvb1989** [comment]
> LGTM, I think this is going to be really nice to have in the product for helping users who are in restricted environments and find themselves wedged. It should help unblock a lot of stuff that previously had very nasty workarounds.

@ellismg , my only concern is what if azd receives some scope that is never used by azd. For example `https://outlook.office.com`  
Maybe we should define the list of valid scopes for azd, which I think are currently only 2 or 3 (arm, msgraph and key vault?)

**Comment by weikanglim** [comment]
@vhvb1989 Do you mean that as a UX concern? Would it be any different than modifying the request parameters in the browser, as we've suggested users to do?

**Comment by vhvb1989** [comment]
> modifying the request parameters in the browser, as we've suggested users to do?

I don't think we have such a suggestion anywhere (docs or issues).

It is definitely much better to support this `--scope` argument than what we had before, I like it. 
On the other hand, what I am thinking is that if `msgraph` is the only ever value that azd will be getting for the `--scope` argument, maybe we could make it easier for customers and make an argument like `azd auth login --msgraph`.  

Then, instead of showing the error and ask folks to run `azd auth login --msgraph`, we could ask folks if they want to re-auth for the operation they are trying to do, and azd would run `azd auth login...` in that moment and then continue the previous operation.

**Comment by weikanglim** [comment]
@vhvb1989 I see. I don't think `msgraph` is the only ever value. Policies could be applied for any AAD resource. It can also happen at a more scoped operation in the future, i.e. `https://graph.microsoft.com/User.ReadWrite.All`. 

For the UX improvement, as you said, I think the solution here is to have interactive login be part of the command flow. Without it, we end up having to expose internal details to users and also require them to perform a multistep operation before continuing where they were. See #2184

**Comment by mattdot** [comment]
Thank you for adding this.  It will allow us to support Power Platform Terraform Provider + AZD.  We have scopes that azd/az are not preauthorized for and are not graph.microsoft.com.

**Pull request merged**
