### PR TITLE
Support .NET App Host Projects

### PR DESCRIPTION
**Pull request by ellismg**
.NET App Host projects can produce a manifest which `azd` can use instead of our existing huristics to determine what resources an application needs.

This change adds support for these projects to our "initialized from an existing codebase flow".

In addition, this feature uses the new support in `azd` for not persisting IaC to disk by default. A new `azd infra synth` command (presently in alpha) is added for folks that want to persist the infrastructure to disk, either to look at it or modify it if there are issues.

### CODE REVIEW

**Review by vhvb1989 — APPROVED** [review]
You're the best

**Review by weikanglim — APPROVED** [review]
Neat to see how cleanly this landed!

**Comment by ellismg** [comment]
> Neat to see how cleanly this landed! I'm glad we were able to integrate this with the existing init from app flow without much trouble!

Thanks, @weikanglim, was a ton of fun working in your part of the tree for a while.  Thanks to both you and @vhvb1989 for your help in the effort.

**Comment by rajeshkamal5050** [comment]
[heart]         Rajesh Kamal reacted to your message:
________________________________

**Pull request merged**
