### PR TITLE
Add secrets param to container-app.bicep

### PR DESCRIPTION
**Pull request by pamelafox**
For my container app (https://github.com/pamelafox/flask-surveys-container-app) I wanted to store the postgres server password as a secret on the app, so I could use secretRef in the environment variables. (I would have stored in KeyVault, but ACA doesn't interact with KeyVault the same way App Service does, apparently). 

In order to do that, I needed to add a secrets param to container-app.bicep and union it with the existing secret for the container registry.

This should not require updates to existing apps since secrets has a default value of empty array.

### CODE REVIEW

**Comment by jongio** [comment]
I believe this means that secrets will be outputted from a different module, which I don't think we want to do in bicep because of the security implications.  Is that correct?

**Comment by pamelafox** [comment]
Hm, for my usage, it meant that a secret flowed from main.parameters.json to web.parameters.json and was then input to the container-app module as a parameter:
https://github.com/pamelafox/flask-surveys-container-app/blob/main/infra/main.bicep#L119
https://github.com/pamelafox/flask-surveys-container-app/blob/main/infra/web.bicep#L25

So you are right, I did output it in main.bicep. Dang. What's the suggested approach? 

This article suggests using the KeyVault SDK, but then that means adding the Azure SDK to an app that didn't previously need it:
https://learn.microsoft.com/en-us/azure/container-apps/manage-secrets?tabs=arm-template

**Comment by jongio** [comment]
Yeah, KV is the recommended approach.  Was the app not using any azure services?

**Comment by pamelafox** [comment]
No, it wasn't using Azure services. Most of my apps don't, since I'm assuming developers want cloud portability when possible. Secrets management is generally a mess across everywhere though, so if there's no way to securely use secret-ref with azd, I'll try the KV SDK.

[I did briefly try to just put the secret generation in web.parameters.json so that it wouldn't need to be output by main, but that didn't work. Maybe I bungled it though].

**Comment by jongio** [comment]
Okay, so using Azure as a host, but no services.  I'll take a look at the project and think about it.

**Comment by pamelafox** [comment]
Closing this pull request due to the security issue. I've filed https://github.com/Azure/azure-dev/issues/1474 to suggest a different azure-dev enhancement for this use case.

**Pull request closed without merging**
