### PR TITLE
Upgrade oryx

### PR DESCRIPTION
**Pull request by showpune**
Upgrade the oryx builder version

### CODE REVIEW

**Review by vhvb1989 — APPROVED** [review]

**Comment by showpune** [comment]
@vhvb1989 , because the old oryx builder is deprecated and bring error, can you help to merge the PR to use the new builder

**Comment by vhvb1989** [comment]
I was waiting on @weikanglim review.  Let's merge for now

**Comment by vhvb1989** [comment]
thank you @showpune

**Pull request merged**
