### PR TITLE
Remove template: java-postgresql

### PR DESCRIPTION
**Pull request by vhvb1989**
Removing template `todo-java-postgresql` from azure-dev.

Why:
- The template is `private` on Azure-Samples org, only reachable by internal users.
- The template is not within the azd template list, so it is not discoverable by customers.
- This template is `public` from: https://github.com/fangjian0423 at: https://github.com/fangjian0423/todo-java-postgresql-terraform

### CODE REVIEW

**Review by wbreza — COMMENTED** [review]
I defer to @savannahostrowski since I don't know the intent of the template on whether or not it should ever make it to the `Azure-Samples` org or just stay as a user contributed Awesome AZD template.

**Comment by rajeshkamal5050** [comment]
> I defer to @savannahostrowski since I don't know the intent of the template on whether or not it should ever make it to the `Azure-Samples` org or just stay as a user contributed Awesome AZD template.

@vhvb1989 @savannahostrowski I believe the intention was to get them added to https://github.com/Azure/azure-dev/pull/1792, synced to https://github.com/Azure-Samples/todo-java-postgresql-terraform and add to the default list of azd templates.

@yiliuTo @fangjian0423 is that right?

**Comment by yiliuTo** [comment]
Hi @rajeshkamal5050 

> I believe the intention was to get them added in azure-dev https://github.com/Azure/azure-dev/pull/1792, synced to https://github.com/Azure-Samples/todo-java-postgresql-terraform and add to the default list of azd templates.

I think so, but I am not quite sure of the context about this template, maybe we can wait @fangjian0423 for the response when he is back next week?

**Comment by fangjian0423** [comment]
hi @rajeshkamal5050 

> I believe the intention was to get them added in azure-dev https://github.com/Azure/azure-dev/pull/1792, synced to https://github.com/Azure-Samples/todo-java-postgresql-terraform and add to the default list of azd templates.

It should be added in azure-dev. Since the UI, app, build config/codes are exactly the same as what we have for other java templates. The delta just being the terraform modules.

**Comment by vhvb1989** [comment]
Expecting to update this version and make the template public.

**Pull request closed without merging**
