### PR TITLE
New API Management resources for defining REST and GraphQL APIs

### PR DESCRIPTION
**Pull request by adrianhall**
Example definition in `main.bicep`:

```bicep
module graphqlApi ./core/gateway/apim-graphql-api.bicep' = {
  name: 'graphqlapi'
  scope: rg
  params: {
    name: 'graphql'
    apimServiceName: apim.outputs.apimServiceName
    apimLoggerName: apim.outputs.apimLoggerName
    serviceUrl: '${api.outputs.SERVICE_API_URI}/graphql'
    policy: loadTextContent('../src/api-management/graphql.policyxml')
    schema: loadTextContent('../src/schema.graphql')
  }
}
```

Similar thing for REST, except instead of a `schema` element:

```bicep
definition: loadTextContent('../src/openapi.yml')
```

### CODE REVIEW

**Comment by jongio** [comment]
LGTM - @wbreza ?

**Review by wbreza — COMMENTED** [review]
This all looks good, but testing the app @ https://github.com/adrianhall/todo-graphql-csharp-appservice-cosmos I am seeing 400 errors from the frontend making requests to the APIM graphql backend.  

Is that repo using the same bicep?

**Comment by adrianhall** [comment]
I'm still working on the actually application in the repo (there are some GraphQL errors being sorted).  The infra is solid though.

**Comment by springcomp** [comment]
@adrianhall @wbreza

This is a bug in Azure API MAnagement. It does not support variables with complex types (arrays / objects) but only scalar variables. Azure API Management does not correctly use the underlying GraphQL.Net library the `<validate-graphql-request />` policy is built upon, unfortunately.

**Comment by adrianhall** [comment]
> @adrianhall @wbreza
> 
> This is a bug in Azure API MAnagement. It does not support variables with complex types (arrays / objects) but only scalar variables. Azure API Management does not correctly use the underlying GraphQL.Net library the `<validate-graphql-request />` policy is built upon, unfortunately.

Unfortunately, it's not that simple.  I'll take this offline.

@wbreza - just leave this PR here for right now, if you could.  I'll reply again once the entire app has been tested with the code.

**Review by vhvb1989 — APPROVED** [review]
LGTM, but I'd wait on @jongio and @weikanglim

**Comment by jongio** [comment]
> LGTM, but I'd wait on @jongio and @weikanglim

I'll review when @adrianhall says ready for review

**Comment by adrianhall** [comment]
Closing as I have a brand new set (see azure-samples/api-management-sample-apis) that are more tested.  I'll put in a new PR for these once the current release is finished rolling out.

**Pull request closed without merging**
