### PR TITLE
Build cmd.exe command line directly

### LINKED ISSUE #2727: [Issue] Unable to use azd up when parenthesis in username
- [ ] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

**Output from `azd version`**
azd version 1.3.0 (commit 6605c5768cb3ab6d9e0e6c2d892c9e8b49e1f720)

**Describe the bug**
Unable to run azd up when there are Parenthesis in the username
image

**To Reproduce**
Make sure you have a userfolder with parenthesis in the name like
c:\users\XX(x)XX

**Expected behavior**
That azd up would just run and deploy the bicep also when there are parenthesis in the username

**Environment**
Information on your environment:
    * Windows 11
    * VSCode

### PR DESCRIPTION
**Pull request by vhvb1989**
When using the shell to run a command on Windows, we were not properly
quoting arguments that we passed to cmd.exe. This could cause errors in
cases where paths to command or arguments contained parenthesis.

To address this, we no longer rely on Go's quoting of arguments and
instead set the CmdLine field of SysProcAttr on Windows, with a command
line quoted as `cmd.exe` expects.

As part of this change, I also fixed an issue where we were not flowing
the context object to the subcommand when we were using the shell to run
the command instead of invoking it directly.

A small end to end test is included to ensure we can invoke programs
when they live in directories that have `()`'s in their names, as we we
saw in #2727 where the downloaded version of bicep is cached into the
user's folder, and the user name contained `()`.

Fixes #2727
Fixes https://github.com/Azure/azure-dev/issues/3199

### CODE REVIEW

**Comment by vhvb1989** [comment]
updating https://github.com/Azure/azure-dev/pull/2733/files to fix https://github.com/Azure/azure-dev/issues/3199

Tested that this fix from Matt works :)

**Comment by ellismg** [comment]
I think last time I took a run at this there were still some quoting issues on windows and I didn't have the best environment for doing a quick turn-around on fixing them.

I do think that independent of this change we should think about if our strategy of always running windows stuff via a shell was the right move - I think folks are going to find it super strange.

**Review by ellismg — APPROVED** [review]
LGTM, thanks for bringing this back to life and getting it across the finish line, @vhvb1989 .

**Review by weikanglim — APPROVED** [review]

**Comment by vhvb1989** [comment]
Found more issues while trying to make this work. 

Moved to this other approach for https://github.com/Azure/azure-dev/issues/3199

**Pull request closed without merging**
