### PR TITLE
Write telemetry data for Windows Installer package

### PR DESCRIPTION
**Pull request by heaths**

### CODE REVIEW

**Comment by heaths** [comment]
Should switch to using https://nuget.info/packages/WixToolset.DUtil instead. Safer and easier than maintaining necessary helper functions.

**Comment by heaths** [comment]
@danieljurek this basically completes the work, but there's one behavior I wanted feedback on. Whenever `INSTALLEDBY` is passed we'll write that value. If the file exists it's overwritten. If the file exists but the property is not passed, the file remains as-is. Would you want that value retained, or if `INSTALLEDBY` is not passed should I delete the file thus signalling it wasn't upgraded (or repaired, etc.) by any supported chainer.

**Comment by danieljurek** [comment]
In think in the base case we should use `MSI` if no value is provided to `INSTALLEDBY`. There are still the scenarios of "downloading binary directly" (likely rare) and "built azd from source" (probably rare outside of our own dev/testing loops). 

The telemetry should report the most recent install method used for the running version of `azd`. 

Scenarios I'm seeing: 

1. Downloaded the binary file directly (no `.installed-by.txt`) -- Return an empty string in telemetry
2. Compiled azd from source -- Return an empty string
3. MSI 
    1. provided no INSTALLEDBY -- `.installed-by.txt` content: `MSI`
    2. provided some value to 1INSTALLEDBY1 -- Use that value (signifies install source like install-azd.ps1, choco, winget, etc.)
4. Install script (`.sh`) -- .`installed-by.txt` content: `install-azd.sh`
5. .deb/.rpm package -- `.installed-by.txt` content: `deb` or `rpm`

I think if we see too many empty values in `.installed-by.txt` then we'd need to work out how to further subdivide that category.

@ellismg, what do you think?

**Review by danieljurek — APPROVED** [review]
Local testing of PR outputs LGTM. `.installed-by.txt` ends up in the right folder and with the expected content. Dashes are supported (e.g. `INSTALLEDBY=value-with-dashes`). 

Automated verification can be added as part of wiring up the install scripts.

**Pull request merged**
