### PR TITLE
Add provision command to the Azure Resources "create resources" menu.

### LINKED ISSUE #924: [Issue] Add with "Create with the Azure Developer CLI" to the resource creation options
With the Azure Tools extension pack installed, a developer can create a new resource by clicking on the + in the resources pane. Once they click the button, they are provided with options (see below).

image

We should add an option to that says (I'm open to suggestions on the wording):
> Create with the Azure Developer CLI (azd)...
Use the Azure Developer CLI to set up all application resources

Upon clicking this, we trigger `azd provision` to create all the resources for the user based on their IaC assets in their project's infra/.

### PR DESCRIPTION
**Pull request by philliphoff**
Add the `azd provision` command to the "create resources" menu of the Azure Resources view.

Screenshot 2022-10-21 at 10 10 41

Resolves #924

### CODE REVIEW

**Review by jongio — APPROVED** [review]

**Comment by karolz-ms** [comment]
At a first glance it is not very clear to me what the command does. The title tells me that AZD is involved, but what resources are created--that part is not clear.

Perhaps something like "Create application infrastructure resources (azd provision)..." would be better?

**Comment by philliphoff** [comment]
> Perhaps something like "Create application infrastructure resources (azd provision)..." would be better?

(edit) Also, the subtitle says "Use azd to set up all application resources", which is not the case--"provision" only creates "infra" resources

@savannahostrowski Have any feedback on Karol's suggestion? Sounds reasonable to me.

**Comment by savannahostrowski** [comment]
Yeah - I think that's fair feedback and that it's probably worth trying to increase the specificity of the wording.

Maybe we can do this for the top level header + subtext:

>"Create application infrastructure using azd..."
"Use the Azure Developer CLI to set up application infrastructure resources (azd provision)"

**Comment by philliphoff** [comment]
Updated text:

Screenshot 2022-10-21 at 11 50 47

**Review by ellismg — APPROVED** [review]

**Pull request merged**
