### PR TITLE
Add err to message for help with debugging login issue

### PR DESCRIPTION
**Pull request by pamelafox**
Adding err to the message to provide some insight on what's happening in https://github.com/Azure/azure-dev/issues/1365

### CODE REVIEW

**Comment by weikanglim** [comment]
hey @pamelafox thanks for logging the issue and submitting a fix. I also took the opportunity to fix the erroneous log message that you were seeing with `AZD_DEBUG`.

Would you be willing to run the private bits once `azure-dev - cli` CI build completes? With the error message uncovered, we might need to make another fix to address the root cause.

Otherwise, I suspect the issue might related to dir/file permissions. You could see if rerunning with `sudo` works, and if so, follow https://learn.microsoft.com/en-us/azure/developer/azure-developer-cli/troubleshoot#azd-init-requires-sudo to remove and have `azd` recreate the folder.

**Comment by pamelafox** [comment]
Result of running:

```
2023/01/12 11:20:51 middleware.go:106: running middleware 'debug'
2023/01/12 11:20:51 middleware.go:106: running middleware 'telemetry'

ERROR: logging in: failed saving configuration. failed writing configuration data: open /Users/pamelafox/.azd/config.json: permission denied
```

So I followed the FAQ you suggested, rm'ed the file, and it works subsequent time:

```
2023/01/12 11:21:46 main.go:251: updated cache file to version 0.5.0-beta.1 (expires on: 2023-01-13T19:21:46Z)
2023/01/12 11:21:48 cache.go:22: ignoring error in adapter: open /Users/pamelafox/.azd/auth/msal/cache.json: no such file or directory
2023/01/12 11:21:48 manager.go:150: creating empty config since '/Users/pamelafox/.azd/config.json' did not exist.
```

So I guess it's not a new issue, but I think it's still a good thing to show the err as this PR does, as that might have led me down the sudo path more readily.

**Review by weikanglim — APPROVED** [review]

**Comment by weikanglim** [comment]
> So I guess it's not a new issue, but I think it's still a good thing to show the err as this PR does, as that might have led me down the sudo path more readily.

@pamelafox Absolutely! And I don't mean to suggest otherwise :). Thanks for the contribution. Merging this now.

**Pull request merged**
