### PR TITLE
remove the code for picking services

### PR DESCRIPTION
**Pull request by vhvb1989**
fix: https://github.com/Azure/azure-dev/issues/3608
fix: https://github.com/Azure/azure-dev/issues/3280
fix: #3284

### CODE REVIEW

**Review by ellismg — APPROVED** [review]
There is also this code in: `environment_service_create.go`

https://github.com/Azure/azure-dev/blob/733bfdc26c871be4e9b3e077069a6e0d209c837d/cli/azd/internal/vsrpc/environment_service_create.go#L116-L126

We should be able to remove this now as well.

Otherwise, LGTM!

**Review by weikanglim — APPROVED** [review]
LGTM

**Comment by rajeshkamal5050** [comment]
@davidfowl @mitchdenny FYI, we are removing the external services handling from Azd and its integration with VS Publish flow. VS has already removed it.

**Review by rajeshkamal5050 — CHANGES_REQUESTED** [review]
Aspire core PR https://github.com/dotnet/aspire/pull/3278 for Preview-5 has breaking changes. Consume those changes and test too.

**Comment by vhvb1989** [comment]
@rajeshkamal5050 , the breaking changes are covered here: https://github.com/Azure/azure-dev/pull/3612

**Pull request merged**
