### PR TITLE
[Merge for 1.5.1] Update azure.yaml.json so support docker build target

### PR DESCRIPTION
**Pull request by Petermarcu**
Updating azure.yaml schema to support docker build target

### CODE REVIEW

**Review by wbreza — APPROVED** [review]
Looks good.  We should hold off merging this in till right before next release since we still don't have a good versioning story for our yaml schema.  Our schema endpoints in the auzre.yaml point directly to the `main` branch raw JSON file.

**Comment by Petermarcu** [comment]
@danieljurek do we know why the check enforcer check is stuck here?

**Comment by ellismg** [comment]
> @danieljurek do we know why the check enforcer check is stuck here?

It's "stuck" because we have no jobs that are triggered off of these files (since we don't have any CI legs that validate them) so it is just waiting for some jobs to show up and pass, which will never happen.

/check-enforcer override

Per, @wbreza's comment, we should merge then on 12/12 when we cut `1.5.1`.

**Comment by Petermarcu** [comment]
Ok, I'll let you hang onto this and merge at the right time.

**Pull request merged**
