### PR TITLE
I accidentally a word

### PR DESCRIPTION
**Pull request by bwateratmsft**

### CODE REVIEW

**Review by danieljurek — APPROVED** [review]

**Review by ellismg — APPROVED** [review]

**Review by wbreza — APPROVED** [review]

**Comment by bwateratmsft** [comment]
Most reviewed PR in history

**Review by jongio — APPROVED** [review]

**Review by weikanglim — APPROVED** [review]
Wanted to jump on the record breaking train for review approvals

**Review by savannahostrowski — APPROVED** [review]
I wanted to be here too!

**Review by karolz-ms — APPROVED** [review]
Could not miss it! 😆

**Pull request merged**
