### PR TITLE
aspire: Write all manifests under AppHost folder

### PR DESCRIPTION
**Pull request by ellismg**
Previously when running `azd infra synth` to write out the infrastructure for an Aspire application, we'd write the container app manifests into files named `containerApp.tmpl.yaml` in a `manifests` directory under the project folder for the individual project.

This change adopts a new strategy, now we instead create a single `infra` folder, next to the AppHost project and write the container app manifest for every `project.v0` and `dockerfile.v0` resource into that folder, named after their aspire resource name (i.e. the first argument passed to `AddProject`) with the `.tmpl.yaml` suffix.

This prepares us for a future change where we will move the IaC for `container.v0` resources out of the `resources.bicep` file and into individual manifests per resource in this same folder.

It also allows the same project to be reference by two separate app hosts and then `infra synth` both of them without having collisions. This isn't something that is commonly done today but the flexibility is nice.

### CODE REVIEW

**Review by vhvb1989 — APPROVED** [review]

**Comment by davidfowl** [comment]
Trying this out on the aspire starter template and I don't see the projects in the infra folder.

**Comment by davidfowl** [comment]
Ahh, I was expecting to see them under the infra folder. Why not put all the infra under the apphost project? Why split it across 2 folders? Is this to make it work with existing azd scenrios?

**Comment by davidfowl** [comment]
image

Can we see how much work it would be to put it all under an infra folder under the apphost?

**Comment by ellismg** [comment]
> Can we see how much work it would be to put it all under an infra folder under the apphost?

It would not be much work.  I can make the change.

**Comment by ellismg** [comment]
> Is this to make it work with existing azd scenrios?

Sort of - we used `manifests` because that what we used for some of our k8s targets, where `manifests` was a much more natural name.  When I started doing the work here initially I reused the `manifests` name since these felt more like k8s manifests than bicep files.  But I know long term the plan is to move these to be bicep files (post Aspire 8.0) so centralizing on "infra" right now seems reasonable.

**Comment by ellismg** [comment]
@davidfowl The new build above should write (and read) these files from the `infra` folder SxS with the app host now.

**Comment by davidfowl** [comment]
Even the bicep files?

**Comment by davidfowl** [comment]
OK I pulled this, but I'd like to see the following changes (tell me how difficult they are to make):

All of the Infra is tied to the env apphost. That means every resource expressed in the apphost is emitted as a bicep or yaml file with the resource name. That means removing main.bicep and resources.bicep out of the root and into the app host sub folder.

image

Instead, could we do:

image

**Comment by rajeshkamal5050** [comment]
> Instead, could we do:
> 
> image

Yes David, I believe @ellismg and @weikanglim are trying to split them into multiple PR's.
- getting manifests moved under app host's infra/ - current one
- handling multiple app host's - another pr https://github.com/Azure/azure-dev/pull/3803
- change container.v0 resource from bicep to yaml - coming soon. This will also contain move(all bicep also under app host infra/)? @ellismg 

cc @vhvb1989

**Review by rajeshkamal5050 — APPROVED** [review]

**Review by rajeshkamal5050 — CHANGES_REQUESTED** [review]
Let's merge this post 1.8.2 release (Apr/30) given there are follow-up changes w.r.t consolidating bicep and manifest files under app-host infra/

**Review by rajeshkamal5050 — APPROVED** [review]

**Pull request merged**
