### PR TITLE
Oryx builder upgrade: Use the standard builder

### PR DESCRIPTION
**Pull request by showpune**
The mcr.microsoft.com/oryx/builder:aca-debian-bullseye-20240424.1 is used to run in cloud environment, local builder should use the standard one mcr.microsoft.com/oryx/builder:debian-bullseye-20240424.1

### CODE REVIEW

**Review by yilims — APPROVED** [review]

**Comment by showpune** [comment]
@weikanglim , I checked the log and it seems not related with the change and can you help to approve the PR? 
It is urgent as the old orxy builder doesn't work

**Review by weikanglim — APPROVED** [review]

**Review by vhvb1989 — APPROVED** [review]

**Pull request merged**
