### PR TITLE
Add template tests

### PR DESCRIPTION
**Pull request by danieljurek**

### CODE REVIEW

**Review by wbreza — APPROVED** [review]
LGTM

**Review by ellismg — APPROVED** [review]
LGTM - I suspect we will also want a version of this job at some point that uses `azd` built from head, instead of the last release - but this is already very cool!

**Comment by danieljurek** [comment]
@ellismg -- Definitely something we'd like to be able to do in the future. https://github.com/Azure/azure-dev/issues/182

**Pull request merged**
