### PR TITLE
Notice manual update

### PR DESCRIPTION
**Pull request by vhvb1989**
Used artifacts from: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2609001&view=artifacts&pathAsName=false&type=publishedArtifacts

Build from: Mar 6, 2023 at 9:15 AM PST

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2609001&view=results

### CODE REVIEW

**Review by wbreza — COMMENTED** [review]
What tool(s) are we using to generate this?

**Comment by ellismg** [comment]
> What tool(s) are we using to generate this?

I believe this is generated by [this](https://dev.azure.com/azure-sdk/internal/_build?definitionId=4651) internal pipeline.  There is some common automation that looks at all your dependencies and then generates this document.

**Review by weikanglim — APPROVED** [review]

**Pull request merged**
