### PR TITLE
Update the infra/core modules to AVM modules of "todo-nodejs-mongo"

### PR DESCRIPTION
**Pull request by dotnet-7**
Update the infra/core modules to AVM modules for `todo-nodejs-mongo`.

**1. Modules not replaced by AVM**
  - **Cosmos DB**: Missing the feature `Microsoft.KeyVault/vaults/secrets` and the output `connectionStringKey`, so we cannot store the `connection string` into keyvault.
 AVM issue link: https://github.com/Azure/bicep-registry-modules/issues/632

- **Monitoring (app insights)** : Missing the feature `Microsoft.Portal/dashboards` and the output `applicationInsights.properties.ConnectionString`.
AVM issue link: https://github.com/Azure/bicep-registry-modules/issues/1130

- **APIM**: Missing features `Microsoft.ApiManagement/service/loggers`, `Microsoft.ApiManagement/service/apis/diagnostics`.
AVM issue link: https://github.com/Azure/bicep-registry-modules/issues/1124

**2. Modules replaced by AVM**
- **App Service**
- **Key Vault**
- **App Service Plan**

@jongio for notification.

### CODE REVIEW

**Review by vhvb1989 — APPROVED** [review]
LGTM and tests passed

**Review by wbreza — COMMENTED** [review]
I have no issue adopting AVM and migrating away from our home grown core modules.  
If we move forward we should update all the templates and deprecate the core modules.

One way to approach this would be to PR into a feature branch and then merge the feature branch back into main when these updates are completed.

**Comment by vhvb1989** [comment]
> I have no issue adopting AVM and migrating away from our home grown core modules. If we move forward we should update all the templates and deprecate the core modules.
> 
> One way to approach this would be to PR into a feature branch and then merge the feature branch back into main when these updates are completed.

Repoman does the branch on each template automatically.  Shouldn't it be a duplication to branch azure-dev as well?
Keep in mind that we are updating the todo-templates, while the core modules are still available for anyone from the repo.  We can keep those around for a while

**Review by jongio — CHANGES_REQUESTED** [review]

**Comment by jongio** [comment]
Please try to make this work without any modules from infra/core.  I want to see what all the gaps look like

**Comment by v-jiaodi** [comment]
@jongio I have updated the code, please review.

There are two questions that need to be clarified:
1.For `applicationInsightsDashboard`, `Microsoft.ApiManagement/service/loggers` and `Microsoft.ApiManagement/service/apis/diagnostics`, since it was not implemented in `AVM`, we have retained the original implementation.
2.Remove apim service sku config. For `Consumption` SKU Type capacity must be specified as `0`, but in `AVM` , only `1` and `2` are allowed: https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/api-management/service/main.bicep#L68

**Comment by jongio** [comment]
> @jongio I have updated the code, please review.
> 
> There are two questions that need to be clarified:
> 
> 1. For `applicationInsightsDashboard`, `Microsoft.ApiManagement/service/loggers` and `Microsoft.ApiManagement/service/apis/diagnostics`, since it was not implemented in `AVM`, we have retained the original implementation.
> 2. Remove apim service sku config. For `Consumption` SKU Type capacity must be specified as `0`, but in `AVM` , only `1` and `2` are allowed: https://github.com/Azure/bicep-registry-modules/blob/main/avm/res/api-management/service/main.bicep#L68
> 3. For cosmosConnectString, we store in keyVault by `listConnectionStrings(resourceId, '2022-08-15').connectionStrings[0].connectionString`

Can you please reference the issues that we have filed for each of the above?

**Comment by v-jiaodi** [comment]
@jongio 
1. **Monitoring (app insights)** : Missing the feature `Microsoft.Portal/dashboards`, since it was not implemented in `AVM`, we have retained the original implementation. https://github.com/Azure/bicep-registry-modules/issues/1130
2. **APIM**: Missing features `Microsoft.ApiManagement/service/loggers` and `Microsoft.ApiManagement/service/apis/diagnostics`.
https://github.com/Azure/bicep-registry-modules/issues/1124

**Pull request closed without merging**
