### PR TITLE
Remove `azure-dev.yml` workflow files from bicep/terraform starters.

### LINKED ISSUE #4344: bicep/terraform starters containing `azure-dev.yml` workflow files
With #4013 landed, should we remove workflows from the starters (i.e. bicep starter, terraform starter) that don't have application code in them? They should look exactly the same as what `azd pipeline config` would generate when it runs (we should verify if it doesn't match).

The template repositories:
- [Bicep starter](https://github.com/Azure-Samples/azd-starter-bicep)
- [Terrraform starter](https://github.com/Azure-Samples/azd-starter-terraform)

There are four files under the [templates/common](https://github.com/Azure/azure-dev/blob/d91c73968473a807d992560ab6db5b6a192a1447/templates/common) directory I believe that could be removed with this change.

### PR DESCRIPTION
**Pull request by zedy-wj**
Fixes #4344

Remove `azure-dev.yml` workflow files from bicep/terraform starters.

**Notes:** The CI errors are related to the subscription.
```
{
  "error": {
    "code": "ReadOnlyDisabledSubscription",
    "message": "The subscription '3819cb9d-0f7c-4284-9e93-220e7fb2367a' is disabled and therefore marked as read only. You cannot perform any write actions on this subscription until it is re-enabled."
  }
}
```

@weikanglim, @rajeshkamal5050 for notification.

### CODE REVIEW

**Comment by weikanglim** [comment]
@v-xuto @rajeshkamal5050 I did find an issue with Terraform, but it's a separate issue with `pipeline config`. I created #4435.

I think we should wait on this -- otherwise the Terraform starter just won't work.

**Review by wbreza — APPROVED** [review]

**Review by vhvb1989 — CHANGES_REQUESTED** [review]
This change is removing the definition for all templates. It should only remove it from the starters, as the title mentions it.

**Comment by zedy-wj** [comment]
> This change is removing the definition for all templates. It should only remove it from the starters, as the title mentions it.

Removing workflow from all templates to starters only.

**Review by vhvb1989 — APPROVED** [review]

**Comment by rajeshkamal5050** [comment]
@vhvb1989 @hemarina can we make sure build, template tests are ✅ and then merge this PR?

**Pull request merged**
