### PR TITLE
Cloudshell auth

### PR DESCRIPTION
**Pull request by danieljurek**
Retrieves credentials using the token endpoint on CloudShell https://learn.microsoft.com/en-us/azure/cloud-shell/msi-authorization. The endpoint handles caching of the token so it can be requested without having to handle caching logic inside the application. 

Also reports telemetry that it's in CloudShell. This detection is done using an environment variable `AZD_IN_CLOUDSHELL` whose name we can control. 

I had to refactor some logic around JWT parsing to prevent a circular dependency in `azureutil`

### CODE REVIEW

**Review by vhvb1989 — APPROVED** [review]
LGTM, but please wait after we release 0.8 to merge? (4/10)

**Review by rajeshkamal5050 — CHANGES_REQUESTED** [review]
@danieljurek Lets merge this change post 0.8 release.

**Review by ellismg — APPROVED** [review]
Great work here, @danieljurek!

**Review by weikanglim — APPROVED** [review]
LGTM. Nice job!

**Pull request merged**
