### PR TITLE
support "azure.openai.account.v0" on netAspire prev4

### PR DESCRIPTION
**Pull request by vhvb1989**
.netAspire preview4 missed (this change)[https://github.com/dotnet/aspire/pull/2529] for using bicep.v0 instead of "azure.openai.account.v0".  This means `azd 1.7.0` does not support the type, as it is expecting bicep.v0.

The changes on this PR make it possible to target azd 1.7.1 to support the type.

### CODE REVIEW

**Comment by mitchdenny** [comment]
I think realistically this will still be broken for P4 from a deployment perspective, because the we don't have Open AI deployment resources listed in the manifest, so so we don't create the deployments in Azure which means the app when deployed won't work.

**Comment by mitchdenny** [comment]
P5 obviously solves this :)

**Review by weikanglim — APPROVED** [review]
Neat!

**Comment by vhvb1989** [comment]
closing in favor of Aspire P5

**Comment by markjbrown** [comment]
I just tried the daily bits with this fix and get the same error.

Here is the exception and the version of azd I'm running.

Is there a way I can just have azd ignore OpenAI here? At this point am fine just getting this deployed without OpenAI.

image
image

**Pull request closed without merging**
