### PR TITLE
Automatically set `ErrorActionPreference` to `Stop` for pwsh inline hooks

### LINKED ISSUE #2170: Set "continueOnError" to `false` script errors cant't stop execution of AZD in Windows
**Describe the issue:**
For azd hook test, when set the "continueOnError" flag to `false`, script errors can not control stop execution of AZD. example as follow:
image

**Repro Steps:**

1. Clone template `todo-nodejs-mongo` to local.
2. Add hook config in `azure.yaml` (Execute a script with errors). 
   
image

3. Run azd command to trigger hook.(eg. `azd package`)

**Environment:**

- OS: Windows desktop.
- Template: todo-nodejs-mongo
- Azd version: 0.8.0-beta.3-daily.2763383  (commit https://github.com/Azure/azure-dev/commit/3f484a283b309b3cab6f91386a4a7af7f4a082a2)

**Expected behavior:**
 When set the "continueOnError" flag to `false`, script errors can control stop execution of AZD

@rajeshkamal5050 for notification.

### PR DESCRIPTION
**Pull request by wbreza**
Fixes #2170 

More information about the `ErrorActionPreference` can be found in the [docs](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-7.3#erroractionpreference)

> Error handling influenced from [GitHub](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference)

### CODE REVIEW

**Comment by weikanglim** [comment]
What about external scripts?

In case you're curious about how GitHub does it:

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference

**Review by ellismg — COMMENTED** [review]
I'll admit that I don't love that we are now injecting stuff into the user's inline scripts without it really being visible, but my reading of the linked issue makes it seem like the alternate is really: "Even if your inline script contains just a single command and that command fails, we will think the hook "passed" because of the out of the box Powershell behavior" and that feels even worse.

The fact that the inline script could go and just reset the error action preference if it wanted to is also nice.

It would be good for us to document this somewhere.

An interesting side effect is I think this would make any intermediate failure in the script terminate the script, which is different from what we have with Bash.  Should we add `set -e` to the Bash preamble?

**Comment by wbreza** [comment]
> What about external scripts?
> 
> In case you're curious about how GitHub does it:
> 
> https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference

Thanks @weikanglim - I've gone ahead and applied the same to our scripts.

**Review by weikanglim — APPROVED** [review]
LGTM. Let's do follow-up to document this.

**Pull request merged**
