### PR TITLE
Enhancement of Terraform modules for App Service - Enable free plan

### PR DESCRIPTION
**Pull request by lechnerc77**
## Content

This PR contains the changes necessary for a user to use the Azure App Service with a free plan. This plan is special as it comes with limitation concerning some settings, namely the `always_on` and the support of 64 bit workers. 
The PR therefore exposes these configurations as variables and propagates the variables to the core modules.

The Terraform variables are defaulted and consequently optional.  They contain the default values of the current setup. Introduction of the variables is therefore *not* a breaking change.

## Reason

This setup might be useful for `azd` templates that serve as quickstarter or for demos/lessons at schools/universities to keep the cost of the setup at a minimum. 

## Additional information

The `.bicep` modules already contain the  necessary parameters. So this PR synchronizes the options available for the supported IaC variants.

### CODE REVIEW

**Comment by vhvb1989** [comment]
related: https://github.com/Azure/azure-dev/issues/1460

**Comment by jongio** [comment]
Should we default to free?

**Comment by lechnerc77** [comment]
> Should we default to free?

From what I have seen in our quickstarter repository, I would stick to the plan `B1` for the `azd` templates, as the experience is better (due to the `always_on` setting). As with this PR you can reconfigure things for the free and shared plans I think this is okay.

**Review by jongio — APPROVED** [review]

**Comment by jongio** [comment]
Can we do the same for bicep templates?

**Comment by lechnerc77** [comment]
@jongio The bicep template was already in perfect shape for adding the free plan. No adoptions needed there.

**Comment by vhvb1989** [comment]
@lechnerc77 , please see the error messages from Terraform:

```

╵

╷
│ Error: Unclosed configuration block
│ 
│ On modules/appservicepython/appservicepython_variables.tf line 59: There is
│ no closing brace for this block before the end of the file. This may be
│ caused by incorrect brace nesting elsewhere in this file.
╵

╷
│ Error: Unclosed configuration block
│ 
│ On modules/appservicepython/appservicepython_variables.tf line 59: There is
│ no closing brace for this block before the end of the file. This may be
│ caused by incorrect brace nesting elsewhere in this file.
╵


╷
│ Error: Unclosed configuration block
│ 
│ On modules/appservicepython/appservicepython_variables.tf line 59: There is
│ no closing brace for this block before the end of the file. This may be
│ caused by incorrect brace nesting elsewhere in this file.
╵

╷
│ Error: Unclosed configuration block
│ 
│ On modules/appservicenode/appservicenode_variables.tf line 59: There is no
│ closing brace for this block before the end of the file. This may be caused
│ by incorrect brace nesting elsewhere in this file.
╵



ERROR: planning deployment: planning infrastructure provisioning: terraform init failed:  , err: failed running terraform init:  (exit status 1)

### ERROR: Dev container exec failed (exit code: 1)
```

**Comment by vhvb1989** [comment]
Trying closing missing bracket as simple fix

**Comment by lechnerc77** [comment]
> Trying closing missing bracket as simple fix

Seems to have worked, right? Sorry for that glitch!

**Comment by vhvb1989** [comment]
blocked by: https://github.com/Azure/azure-dev/pull/1764

**Pull request merged**
