### PR TITLE
Fix typos in ps1 scripts

### PR DESCRIPTION
**Pull request by LukaszKokot**
I was scrolling through the ps1 files and noted some typos that I fixed here.

### CODE REVIEW

**Review by vhvb1989 — APPROVED** [review]

**Comment by weikanglim** [comment]
@danieljurek Any thoughts on this one? Do we end up mirroring these files from upstream anyways?

**Comment by ellismg** [comment]
> @danieljurek Any thoughts on this one? Do we end up mirroring these files from upstream anyways?

Daniel didn't get a chance to respond to this, but I actually know the answer here.  These are not the authoatiative copies of these files.  Instead, they are synced from https://github.com/Azure/azure-sdk-tools/tree/main/eng/common.  We have automation that looks for check-ins there and then opens auto PRs to all the Azure SDK repositories (including ours) to update them.

@LukaszKokot if you want, you can re-raise this PR there.  If not, I should be able to shepherd it over there for you (I'll do the git magic so you remain the author of the commit and get credit for you work here) sometime next week.

Thanks for your contirbution!

**Review by ellismg — CHANGES_REQUESTED** [review]
We need to migrate these changes to azure-sdk-tools, the upstream for these files.  If @LukaszKokot is unable to do this, I'll take care of it the week of 11/13.

Thanks again for your help here, @LukaszKokot!

**Comment by LukaszKokot** [comment]
@ellismg If you can do this, that'd be great, I won't be able to do much the coming weeks. Thank you very much 🙇🏻

**Comment by ellismg** [comment]
Opened the PR in the other repository, closing this since we ultimately won't land it and I no longer need the reminder to go do that.  Thanks again, @LukaszKokot!

**Pull request closed without merging**
