### PR TITLE
Add ability to load azd env vars into shell

### LINKED ISSUE #4067: [Issue] Make it easy to find azd env path
- [X] Make sure you've installed the latest version using [instructions in the wiki](../wiki/install)

I want to easily get the azd env path, so that I can load that into my Python program's environments *without* doing an export. This is what I'm doing now:

```
def load_azd_env():
    """Get path to current azd env file and load file using python-dotenv"""
    result = subprocess.run("azd env list -o json", shell=True, capture_output=True, text=True)
    if result.returncode != 0:
        raise Exception("Error loading azd env")
    env_json = json.loads(result.stdout)
    env_file_path = None
    for entry in env_json:
        if entry["IsDefault"]:
            env_file_path = entry["DotEnvPath"]
    if not env_file_path:
        raise Exception("No default azd env file found")
    logger.info(f"Loading azd env from {env_file_path}")
    load_dotenv(env_file_path, override=True)
```

@vhvb1989 suggested that perhaps azd could make an environment variable for the current path.

### PR DESCRIPTION
**Pull request by jongio**
Fixes #4067 

Currently adds -o export to get-values.  We are evaluating other methods / interfaces as well.

```
source <(azd env get-values -o export)
python.py
```

### CODE REVIEW

**Comment by jongio** [comment]
@pamelafox - Once we get a build of azd for this PR can you try it out to see if that helps with your env path scenario?

**Comment by jongio** [comment]
@pamelafox - I also added a new export option to get-values that allows you to eval and set the context.  For example:

`azd env get-values -o export`

will output:

```
export AZURE_LOCATION=eastus2
export AZD_PIPELINE_PROVIDER=github
export AZURE_ENV_NAME=jong-fast-test-api-2
```

So, you can now do:

`eval $(azd env get-values -o export) && python app.py`

app.py
```
import os

def print_azure_env_name():
    azure_env_name = os.getenv('AZURE_ENV_NAME')
    if azure_env_name is not None:
        print(f"AZURE_ENV_NAME: {azure_env_name}")
    else:
        print("AZURE_ENV_NAME environment variable is not set.")

if __name__ == "__main__":
    print_azure_env_name()

```

And that will display the value from the python app.

```
AZURE_ENV_NAME: jong-fast-test-api-2
```

I'm thinking this will work well for apps that have a startup script like a package.json or a python setup file.  

I think this will do away with this type of code: https://github.com/Azure-Samples/azure-search-openai-demo/blob/main/scripts/load_azd_env.sh

**Comment by pamelafox** [comment]
I would be too afraid to use the -export option, as I keep getting into nasty situations due to lingering exported environment variables from previous exports (like from load_azd_env). I'm trying to move away from export in all the repos now.
Maybe theres some situation where it wouldnt lead to tainting the env?

**Comment by pamelafox** [comment]
I've tried this out, and it works well for the positive case, but for the case that nothing satifies the JMESpath query, it seems to give back the string "null" as a result. Is that expected? Feels a bit odd.

**Comment by jongio** [comment]
> I would be too afraid to use the -export option, as I keep getting into nasty situations due to lingering exported environment variables from previous exports (like from load_azd_env). I'm trying to move away from export in all the repos now. Maybe theres some situation where it wouldnt lead to tainting the env?

I'd like to hear more details on what you are facing with exports.

**Comment by pamelafox** [comment]
@jongio When I export the whole environment, and then I do an "azd env set" to another environment, the previous env variables are still around, so my subsequent actions are affected by anything that was set there (particular anything that main.parameters.json or my hooks use). I have to then explicitly unset every variable to get things back to a clean state.

**Pull request closed without merging**
