### PR TITLE
Overwrite unversioned azd.exe on install

### LINKED ISSUE #1406: Upgrade from 0.4.0-beta.1 to 0.5.0-beta.n issues in script
Blog post says: 

> and the output stated that the CLI was updated to the latest version (at that point 0.5.0-beta.1) but it was not. 

https://dev.to/lechnerc77/azure-developer-cli-episode-050-refactoring-ahead-11k6

Investigate. There could be situations where an uninstall is required and those scenarios should be handled or documented.

### PR DESCRIPTION
**Pull request by heaths**
Fixes #1406

### CODE REVIEW

**Comment by danieljurek** [comment]
@heaths -- I tested locally and demonstrated the fix does work in the scenario we uncovered. 

What are the long-term disadvantages of this approach? I want to make sure we're making the right tradeoffs here.

**Comment by heaths** [comment]
It'll overwrite whatever is there regardless of how it was installed. As long as they keep using the MSIs, at least the MSIs will only overwrite older installed products, but versioned files are best. As mentioned in Teams, it's long been best practice to use versioned files as key paths - even the point of bundling a bunch of unversioned files into the same component with a versioned key path in Windows Installer because versions make better comparators.

**Review by ellismg — APPROVED** [review]
LGTM (TIL about https://learn.microsoft.com/en-us/windows/win32/msi/reinstallmode)

**Review by danieljurek — APPROVED** [review]
Thanks again, Heath! 

In the future when we get `azd.exe` versioning properly we can remove `REINSTALLMODE`.

**Comment by heaths** [comment]
> Thanks again, Heath!
> 
> In the future when we get `azd.exe` versioning properly we can remove `REINSTALLMODE`.

I'd wait for after a few releases, though. Off hand, I don't remember how Windows Installer will treat a versioned file over an unversioned file. Given the choice is based on what's present on disk, off hand I'd assume a seemingly "modified" (modified > created) unversioned file won't be replaced by a versioned file.

**Pull request merged**
